### PR TITLE
Switch API to crafatar

### PR DESCRIPTION
**Pull request by CilantroLeaver**

### CODE REVIEW

**Comment by thecatcore** [comment]
Why did you close it?

**Comment by CilantroLeaver** [comment]
I need to be sure that variable author is in the correct form before I send it with the API URL. Was getting weird errors and stuff! Do you send a UUID with the API or a username?

**Comment by thecatcore** [comment]
with a username

**Comment by CilantroLeaver** [comment]
That would explain my problems with building and running. I guess the solution wouldn't be so simple as my change!

**Comment by thecatcore** [comment]
I’ve implemented the fix in 0.8.8

**Pull request closed without merging**
